#!/bin/bash

set -xeo pipefail

apt-get update -qq
apt-get install -qq -y --no-install-recommends \
  bzip2 \
  ca-certificates \
  curl \
  dirmngr \
  git \
  gnupg \
  htop \
  jq \
  libzmq3-dev \
  locales \
  net-tools \
  python-pip \
  python-setuptools \
  python-wheel \
  tcpdump \
  unzip \
  wget \
  xz-utils

pip install cqlsh

rm -rf /var/lib/apt/lists/*
