#!/bin/bash

set -xeo pipefail

# Docker
# https://hub.docker.com/_/docker/

DOCKER_CHANNEL=${1:-stable}
DOCKER_VERSION=${2:-17.12.0-ce}
DOCKER_ARCH=x86_64

if ! curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${DOCKER_ARCH}/docker-${DOCKER_VERSION}.tgz"; then
  echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${DOCKER_ARCH}'";
  exit 1
fi

tar --extract --file docker.tgz --strip-components 1 --directory /usr/local/bin/
rm docker.tgz
